### ISSUE TITLE
Issue in testing

### ISSUE THREAD

**Issue by nitvishnoi** [lucastabelini/PolyLaneNet#66]
Hi,

I am not able to test any tusimple data images, tried with below command.

python test.py --exp_name tusimple --cfg tusimple.yaml --epoch 2 --view

It's keep on throwing me below error.

[2024-01-24 20:36:52,082] [INFO] Starting testing.
[2024-01-24 20:36:54,908] [INFO] Testing iteration: 1/2
[2024-01-24 20:36:55,802] [ERROR] Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Nitin\Desktop\PolyLaneNet\test.py", line 160, in <module>
    _, mean_loss = test(model, test_loader, evaluator, exp_root, cfg, epoch=test_epoch, view=args.view)
  File "C:\Users\Nitin\Desktop\PolyLaneNet\test.py", line 61, in test
    preds = test_loader.dataset.draw_annotation(
  File "C:\Users\Nitin\Desktop\PolyLaneNet\lib\datasets\lane_dataset.py", line 172, in draw_annotation
    cv2.putText(img, str(i), tuple(points[0]), fontFace=cv2.FONT_HERSHEY_COMPLEX, fontScale=1, color=color)
cv2.error: OpenCV(4.8.1) :-1: error: (-5:Bad argument) in function 'putText'
> Overload resolution failed:
>  - Layout of the output array img is incompatible with cv::Mat
>  - Expected Ptr<cv::UMat> for argument 'img'

Any inputs are appriciated.

Thanks,
Nitin

**Comment by alibustami** [comment]
Hi Nitin,

I am trying to test the repo, but I am getting an error thrown on the `test.py` module in line 141 when loading the test dataset:
`FileNotFoundError: [Errno 2] No such file or directory: 'frames/label_data_0531.json'`

could you elaborate more about the content of these json files mentioned on module `tusimple.py` from lines 11 to 16.

Also could you please explain how did you prepare your testing dataset?
thanks,
Ali
